[package]
name = "number_guess"
version = "0.1.0"
authors = ["hydrostaticcog <hydro@lucidia.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.4"
